export const projects = [
  {
    title: "mikemartinmedia.com",
    type: "Business Website",
    description:
      "Mike Martin Media is an multi media production company based in St Louis, Missouri and working all around the world. Mikemartinmedia.com features a sortable video gallery, embedded video content, a blog, and a contact form. The website is integrated with Google Analytics and Google Tag Manager for running ads and monitoring site traffic. Cookie consent management is handled with Cookie Yes. The website was designed by Seafoam Media.",
    technologies: [
      { name: "Next.js", url: "https://nextjs.org/" },
      { name: "Vercel", url: "https://vercel.com/docs" },
      { name: "React", url: "https://react.dev" },
      { name: "Tailwind CSS", url: "https://tailwindcss.com/docs" },
      {
        name: "JavaScript",
        url: "https://developer.mozilla.org/docs/Web/JavaScript",
      },
      { name: "CSS", url: "https://developer.mozilla.org/docs/Web/CSS" },
      { name: "Headless UI", url: "https://headlessui.com/react" },
      {
        name: "Google Tag Manager",
        url: "https://support.google.com/tagmanager/answer/6102821",
      },
      {
        name: "Google Analytics",
        url: "https://support.google.com/analytics/answer/1008015",
      },
      {
        name: "Google Search Console",
        url: "https://support.google.com/webmasters/answer/9128668",
      },
      { name: "Cookie Yes", url: "https://www.cookieyes.com/documentation/" },
    ],
    role: ["Sole Developer"],
    url: "https://mikemartinmedia.com",
    gitHubRepo: "https://github.com/KLong75/mike-martin-media",
    images: {
      mobile: [
        "/images/mmm/mobile/home.jpg",
        "/images/mmm/mobile/drone.jpg",
        "/images/mmm/mobile/blog.jpg",
        "/images/mmm/mobile/contact.jpg",
        "/images/mmm/mobile/education.jpg",
        "/images/mmm/mobile/video-editing.jpg",
      ],
      desktop: [
        "/images/mmm/desktop/home.png",
        "/images/mmm/desktop/drone-logo.png",
        "/images/mmm/desktop/drone.png",
        "/images/mmm/desktop/our-work.png",
        "/images/mmm/desktop/blog-preview.png",
        "/images/mmm/desktop/blog-post.png",
        "/images/mmm/desktop/contact-form.png",
      ],
    },
  },
  {
    title: "thelongemergency.net",
    type: "Band Website",
    description:
      "The Long Emergency is a rock band in St. Louis, Missouri. Their website features a gig calendar, music player, audio downloads, merch store, blog, and contact form. The website is fully responsive and accessible. It is integrated with Vercel Analytics for monitoring site traffic. The website is built with Next.js and Tailwind CSS.",
    technologies: [
      { name: "Next.js", url: "https://nextjs.org/docs" },
      { name: "Vercel", url: "https://vercel.com/docs" },
      { name: "React", url: "https://react.dev" },
      { name: "Tailwind CSS", url: "https://tailwindcss.com/docs" },
      { name: "TypeScript", url: "https://www.typescriptlang.org/docs/" },
      { name: "CSS", url: "https://developer.mozilla.org/docs/Web/CSS" },
      { name: "Vercel Analytics", url: "https://vercel.com/docs/analytics" },
      { name: "EmailJS", url: "https://www.emailjs.com/docs/" },
    ],
    role: ["Sole Developer and Designer"],
    url: "https://thelongemergency.net/",
    gitHubRepo: "https://github.com/RhythmCodeStudio/the-long-emergency",
    images: {
      mobile: [
        "/images/the-long-emergency/mobile/home.jpg",
        "/images/the-long-emergency/mobile/music.jpg",
        "/images/the-long-emergency/mobile/music-2.jpg",
        "/images/the-long-emergency/mobile/music-player.jpg",
        "/images/the-long-emergency/mobile/lyrics.jpg",
        "/images/the-long-emergency/mobile/shows-future.jpg",
        "/images/the-long-emergency/mobile/shows-past.jpg",
        "/images/the-long-emergency/mobile/1-17-2025.jpg",
        "/images/the-long-emergency/mobile/contact.jpg",
      ],
      desktop: [
        "/images/the-long-emergency/desktop/home.png",
        "/images/the-long-emergency/desktop/music.png",
        "/images/the-long-emergency/desktop/lyrics.png",
        "/images/the-long-emergency/desktop/shows-future.png",
        "/images/the-long-emergency/desktop/shows-past.png",
        "/images/the-long-emergency/desktop/contact.png",
        "/images/the-long-emergency/desktop/shows-footer.png",
      ],
    },
  },
  {
    title: "WatchTV",
    type: "Full Stack Application",
    description:
      "WatchTV serves as a central hub for all of a user's subscription streaming accounts. Search for any TV show or movie and link to where it is available online to stream, rent, or buy. Multiple search methods enable users to find what they want to watch and where they can watch it. Users can search all sources or just the ones they are subscribed to. Save titles to a watchlist for later viewing. The watchlist can be filtered by source, type, and genre.",
    technologies: [
      { name: "React", url: "https://react.dev/" },
      { name: "Node", url: "https://nodejs.org/en/docs/" },
      { name: "MongoDB", url: "https://www.mongodb.com/docs/" },
      { name: "Express", url: "https://expressjs.com/en/starter/installing.html" },
      { name: "MUI", url: "https://mui.com/material-ui/getting-started/overview/" },
      { name: "Apollo", url: "https://www.apollographql.com/docs/" },
      { name: "GraphQL", url: "https://graphql.org/learn/" },
      { name: "JSON web tokens", url: "https://jwt.io/introduction/" },
      { name: "bcrypt", url: "https://www.npmjs.com/package/bcrypt" },
      { name: "Mongoose", url: "https://mongoosejs.com/docs/guide.html" },
      { name: "Swiperjs", url: "https://swiperjs.com/" },
      { name: "JavaScript", url: "https://developer.mozilla.org/docs/Web/JavaScript" },
      { name: "HTML", url: "https://developer.mozilla.org/docs/Web/HTML" },
      { name: "CSS", url: "https://developer.mozilla.org/docs/Web/CSS" },
    ],
    role: "Sole Developer and Designer",
    url: "https://streamhub-e4fc2af8fdfc.herokuapp.com/",
    gitHubRepo: "https://github.com/KLong75/stream-hub",
    guestCredentials: {
      email: "guest@email.com",
      password: "Guest#1",
    },
    images: {
      mobile: [
        "/images/watch-tv/mobile/home.jpg",
        "/images/watch-tv/mobile/login.jpg",
        "/images/watch-tv/mobile/homepage.jpg",
        "/images/watch-tv/mobile/home-star-wars.jpg",
        "/images/watch-tv/mobile/home-menu.jpg",
        "/images/watch-tv/mobile/rogue-one.jpg",
        "/images/watch-tv/mobile/mando.jpg",
        "/images/watch-tv/mobile/search-menu.jpg",
        "/images/watch-tv/mobile/settings.jpg",
        "/images/watch-tv/mobile/combo-search.jpg",
        // "/images/watch-tv/mobile/signup.jpg",
        
      ],
      desktop: [
        // "/images/watch-tv/desktop/feature.png",
        "/images/watch-tv/desktop/user-home.png",
        "/images/watch-tv/desktop/home.png",
        "/images/watch-tv/desktop/login.png",
        "/images/watch-tv/desktop/mando.png",
        "/images/watch-tv/desktop/rogue-one.png",
        "/images/watch-tv/desktop/diego.png",
        "/images/watch-tv/desktop/search.png",
        "/images/watch-tv/desktop/search-results.png",
        "/images/watch-tv/desktop/title-gallery.png",
      ],
    },
  },
  {
    title: "Musicology",
    type: "Full Stack Application",
    description: "A full stack networking application for musicians. Users can sign up, create a profile describing their musical abilities and interests, make posts on the bulletin board, respond to posts made by other users, and connect with other musicians for creative and business purposes.",
    technologies: [
      { name: "React", url: "https://react.dev/" },
      { name: "Node", url: "https://nodejs.org/en/docs/" },
      { name: "MongoDB", url: "https://www.mongodb.com/docs/" },
      { name: "Express", url: "https://expressjs.com/en/starter/installing.html" },
      { name: "MUI", url: "https://mui.com/material-ui/getting-started/overview/" },
      { name: "React Router", url: "https://reactrouter.com/en/main" },
      { name: "Apollo", url: "https://www.apollographql.com/docs/" },
      { name: "GraphQL", url: "https://graphql.org/learn/" },
      { name: "JSON web tokens", url: "https://jwt.io/introduction/" },
      { name: "bcrypt", url: "https://www.npmjs.com/package/bcrypt" },
      { name: "Mongoose", url: "https://mongoosejs.com/docs/guide.html" },
      { name: "JavaScript", url: "https://developer.mozilla.org/docs/Web/JavaScript" },
      { name: "HTML", url: "https://developer.mozilla.org/docs/Web/HTML" },
      { name: "CSS", url: "https://developer.mozilla.org/docs/Web/CSS" },
    ],
    role: ["Lead Developer", "Project Manager"],
    url: "https://musicology-umekev.herokuapp.com/",
    gitHubRepo: "https://github.com/KLong75/musician-networking-app",
    images: {
      mobile: [
        "/images/musicology/mobile/home.jpg",
        "/images/musicology/mobile/login.jpg",
       
      ],
      desktop: [
        // "/images/musicology/desktop/home.gif",
        // "/images/musicology/desktop/home.png",
        "/images/musicology/desktop/home2.png",
        "/images/musicology/desktop/login.png",
        "/images/musicology/desktop/polka-king.png",
        "/images/musicology/desktop/slash.png",
        "/images/musicology/desktop/signup.png",
      ],
    },
  },
  // {
  //   title: "",
  //   description: "",
  //   technologies: [
  //   ],
  //   role: ["Developer"],
  //   url: "",
  //   gitHubRepo: "",
  //   images: {
  //   mobile: [
  //     "",
  //   ],
  //   desktop: [
  //     "",
  //   ],
  // },
  // },
];
